### PR TITLE
Add pseudodata functionality in hdf5 writer

### PR DESCRIPTION
**Pull request by davidwalter2**
First, an argument "--realData" is added in the setupCombine.py and the data is only written into the combinetf input if this flag is given. This ensures that unblinding does not happen by accident. This is intended to work for the root and hdf5 output.

The second is only supported for the hdf5 writer. Multiple pseudodata sets can be added in the setupCard.py by specifying "--pseudoData HISTNAMES" "--pseudoDataAxes SYSTAXES" "--pseudoDataIdxs SYSTAXESINDICES"
Example:
```
--pseudoData massWeightZ horacenloewCorr --pseudoDataAxes massShift systIdx --pseudoDataIdxs -1 1
```
The -1 here means for all bins from the massWeightZ hist and massShift axis one pseudodata is created, another pseudodata is created for the horacenloewCorr histogram axis systIdx and bin 1. 

To fit the pseudodata an update of combinetf is necessary, the corresponding pull request is opened here: 
https://github.com/bendavid/HiggsAnalysis-CombinedLimit/pull/22

### CODE REVIEW

**Comment by cippy** [comment]
One question when running the root-based version of CardTool (but maybe valid also for the hdf5 one). If I don't use --realData, do I still get at least the data histogram available for plotting in the output (root) file, for instance to plot prefit distributions? 
If not, can we add it?

**Comment by davidwalter2** [comment]
> One question when running the root-based version of CardTool (but maybe valid also for the hdf5 one). If I don't use --realData, do I still get at least the data histogram available for plotting in the output (root) file, for instance to plot prefit distributions? If not, can we add it?

Okay, I have adapted the procedure so that in case "--realData" is not given, in root writing mode the data_obs histogram is still produced. But also a pseudodata histogram is produced with the sum of processes from nominal, and the pseudodata histogram is written in the .txt datacard. So that still the pseudodata/asimov is fit when calling combinetf.py without "-t"

**Comment by davidwalter2** [comment]
This would be ready for merge. 
The CI for this PR
https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/PR331/2023_11_09/unfolding/
is identical with the reference CI
https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/ReferenceRuns/2023_11_09_4cd6279/

**Comment by davidwalter2** [comment]
As expected, no impact on the CI. Good to merge from my side

**Pull request merged**
