### PR TITLE
Make massDiff and mass constraint behaviour more configurable

### PR DESCRIPTION
**Pull request by bendavid**
This is needed to facilitate different combinations of W+Z simultaneous fits for some of the cross checks.

There is also what is technically a fix here to the default/automatic behaviour for the yll-ptll (or yll-ptll+W combined fit) where previously although mZ was correctly constrained, it was constrained with a 100MeV uncertainty instead of the 2.1MeV PDG uncertainty.  Of course when fitting non-mass-sensitive observables this should make very little difference.

This PR should have zero change to the nominal fit or the CI.

### CODE REVIEW

**Comment by bendavid** [comment]
CI is identical except for a tiny change in w-like unfolding

@davidwalter2 the Z mass is supposed to be constrained in this configuration right?  In this case the tiny change can probably be explained by the change from 100 MeV to 2.1 MeV uncertainty on the Z mass.

**Comment by bendavid** [comment]
Ah ok no, I see, the mass is constrained but it was being intentionally set to 10MeV previously.  So this PR unintentionally overrides it and forces it to 2.1MeV.  Let me fix that.

**Comment by davidwalter2** [comment]
Well, I think there is no good reason for 10 MeV, maybe 2.1MeV is also fine. No need to change for me

**Comment by bendavid** [comment]
Ok in that case this would be ready to merge.

**Pull request merged**
