### PR TITLE
update singularity to v34

### PR DESCRIPTION
**Pull request by bendavid**
Major upgrades to python, tensorflow, ROOT

ROOT is now built with C++20 support as well (and jitted code should be processed in C++20 mode by default)

### CODE REVIEW

**Comment by bendavid** [comment]
CI output is identical to the reference except for a small change in spacing on some of the plots, probably related to newer versions of matplotlib, etc

So probably we can move forward with this once the SSH issue in the singularity image is sorted out.  (Syncing of the singularity images to cvmfs is currently stuck, but presumably this will get sorted out tomorrow)

**Comment by bendavid** [comment]
Ok the issues with the singularity image are solved for the moment, and the CI output is still identical apart from the small cosmetic changes on the plots, so this would be ready to merge in principle.  @kdlong @davidwalter2 if you think the small cosmetic changes in the plotting related to updated matplotlib, etc versions are creating additional trouble for the paper preparation we can also hold off on this for now.  What do you think?

**Comment by davidwalter2** [comment]
> Ok the issues with the singularity image are solved for the moment, and the CI output is still identical apart from the small cosmetic changes on the plots, so this would be ready to merge in principle. @kdlong @davidwalter2 if you think the small cosmetic changes in the plotting related to updated matplotlib, etc versions are creating additional trouble for the paper preparation we can also hold off on this for now. What do you think?

It's only affecting slightly the impact plots, right? It's actually fixing the "flow bins" in the unfolding plots. I think it's good to merge

**Comment by bendavid** [comment]
There are some small changes eg. here

https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/PR548/2024_09_30/unfolding/postfit_minus.png

vs

https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/ReferenceRuns/2024_09_30_e0a590d/unfolding/postfit_minus.png

(or is this what you meant by fixing the flow bins?)

**Comment by davidwalter2** [comment]
> There are some small changes eg. here
> 
> https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/PR548/2024_09_30/unfolding/postfit_minus.png
> 
> vs
> 
> https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/ReferenceRuns/2024_09_30_e0a590d/unfolding/postfit_minus.png
> 
> (or is this what you meant by fixing the flow bins?)

Right, this is what I meant with fixing the flow bins, previously we had to set flow=False in the mlphep.hist function, it seems to be default now

**Comment by bendavid** [comment]
Ah ok, it actually looks like they replaced the dashes with a less intrusive small triangle

**Comment by davidwalter2** [comment]
> Ah ok, it actually looks like they replaced the dashes with a less intrusive small triangle

Ah yes, now I see it too

**Pull request merged**
