### PR TITLE
Virtual EW corrections for Z

### PR DESCRIPTION
**Pull request by davidwalter2**
Adding virtual corrections for the Z parameterized in ptll,mll (virtual_ew) or ptl,etal (virtual_ew_wlike)

- A new script [plot_theory_corr.py](https://github.com/WMass/WRemnants/compare/main...davidwalter2:231025_ew?expand=1#diff-73d04df39040e3f57ee2bbb908f23e6c142ff065047bef654576b80ca132a3b1) is added that to make 1d or 2d plots of any of the theory corrections
- New script [scripts/corrections/make_theory_corr_virtual.py](https://github.com/WMass/WRemnants/compare/main...davidwalter2:231025_ew?expand=1#diff-dbe3dee8e647934596d450d9f4b2b22fc20b5832f5bb9215ea37286f74dd5529) for producing the virtual corrections from csv files
- Make set_flow in boostHistHelpers.py functioning to set flow bins to values of closest bins
- Helper functions are added, such as  `output_tools/write_theory_corr_hist`

Required wremnants-data update: https://gitlab.cern.ch/cms-wmass/wremnants-data/-/merge_requests/25

### CODE REVIEW

**Comment by bendavid** [comment]
Is this ready to merge?

**Comment by davidwalter2** [comment]
> Is this ready to merge?

Yes

**Comment by bendavid** [comment]
Looking at the PRValidation there are slight changes to the impacts also for the mW case.  Is this expected?

**Comment by bendavid** [comment]
Ok comparing https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/PR336/2023_11_15/impactsW_group_massShiftW100MeV_noi.png vs reference https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/ReferenceRuns/2023_11_15_52e3bad/impactsW_group_massShiftW100MeV_noi.png

The mW impacts are now very very close, but not quite identical.  EW uncertainty changes from 3.88 to 3.85 MeV.  Is it expected/understood that something was touched here which could have an impact at this level?  (Does the change in treatment of the overflow bins also apply to the horace uncertainty on the W in this case?)

**Comment by davidwalter2** [comment]
> Ok comparing https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/PR336/2023_11_15/impactsW_group_massShiftW100MeV_noi.png vs reference https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/ReferenceRuns/2023_11_15_52e3bad/impactsW_group_massShiftW100MeV_noi.png
> 
> The mW impacts are now very very close, but not quite identical. EW uncertainty changes from 3.88 to 3.85 MeV. Is it expected/understood that something was touched here which could have an impact at this level? (Does the change in treatment of the overflow bins also apply to the horace uncertainty on the W in this case?)

So the difference is that before we had the 200% of the correction from horace as the variation and a scale of 1. Now we have 100% of the correction as variation and the scale is set to 2. With scale I mean the "k" factor that is multiplied as k*log(var/nominal). So I would say this can explain the small difference. The correction file itself is the same

**Pull request merged**
