### PR TITLE
Updates on EW uncertainties

### PR DESCRIPTION
**Pull request by davidwalter2**
- Allow to parameterize the reweighting to be done in mll, pTll for the EW uncertainty
- Add additional observables for EW studies
- Update sample list and cross sections
- Use horace as default for the EW uncertainty, double it's magnitude

wremnants-data has to be updated to get the new corrections

### CODE REVIEW

**Comment by davidwalter2** [comment]
From my side this could be merged

**Comment by bendavid** [comment]
What cross section change is included in the systematic variation now?

**Comment by davidwalter2** [comment]
The ones from powheg documented here:
https://gitlab.cern.ch/cms-wmass/private/issue-tracking/-/issues/34

**Comment by bendavid** [comment]
Ok since the correction is a ratio then only the ratio of cross sections matters I guess?  (the absolute values for powheg and horace are very different because powheg is NLO QCD)

**Comment by davidwalter2** [comment]
Yes only the ratio matters, for the Z this is +1.3% and for the W -0.3%

**Comment by bendavid** [comment]
The wremnants-data update might be problematic before https://github.com/WMass/WRemnants/pull/285 is merged, discussing with @jeyserma

**Comment by jeyserma** [comment]
Yes will push the remaining fixes for the DeepMET PR in a few mins, then we can merge and you can go ahead

**Comment by bendavid** [comment]
Ok so yes let's merge https://github.com/WMass/WRemnants/pull/285 first

**Comment by bendavid** [comment]
This has a conflict with the wremnants-data commit from the deepmet pr.  Should be easy enough to rebase and resolve it.

**Comment by davidwalter2** [comment]
> This has a conflict with the wremnants-data commit from the deepmet pr. Should be easy enough to rebase and resolve it.

Resolved, and the PRValidation looks good I think:
Here the reference run of this morning:
https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/ReferenceRuns/2023_09_08_5eaccd5/
Here the result of this PR:
https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/PR287/2023_09_08/lowPU/

**Pull request merged**
