### PR TITLE
Skip nuisance parameters that would affect no processes when preparing the fit setup 

### PR DESCRIPTION
**Pull request by cippy**
This PR partially reverts https://github.com/WMass/WRemnants/pull/492/files and fixes a bug that was in the previous version of the code.

Usually the code would skip any nuisance that ends up being applied to no process in the list of requested ones. Typically this can happen when excluding processes for tests (e.g. when running with signal only). For lnN syst the logic was bugged because the function deals with the whole set of defined LnN syst, and it was returning as soon as one lone nuisance applied to no process was appearing, while it should just continue and move to the next lnN.
For shape systs the logic is the same but in that case returning is fine, because the corresponding function deals with all nuisance handled by a single call to CardTool.addSystematics (e.g. all effStat, or all Pdfs, which can't be applied to different processes for specific nuisance parameters), so as soon as the first one is found with no associated processes it is necessarily going to find no processes for all the others in that group. 

The current code should properly work also for lowPU now.

**Note**: the part of the code concerned by this PR is entered only when using the root based version of setupCombine, not the hdf5 one. Hence, there is no point in having options to customise what the code should do when lone systematics are found (i.e. whether to raise errors or just continue with a warning). Continuing execution with a warning is the original intended behaviour, though, because this case is expected to happen only when running tests.

### CODE REVIEW

**Comment by cippy** [comment]
All good from CI, also for lowPU, no change seen.

This PR: https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/PR503/2024_07_29/

Reference: https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/ReferenceRuns/2024_07_29_b3ae0fe/

I would propose merging this one before my other PR (after the review is done clearly)

**Comment by bendavid** [comment]
Why is an additional command line argument needed here?

**Comment by bendavid** [comment]
Given that this code is specific to the root output I'm kind of inclined to just take this as the moment to start deprecating it rather than introducing more options which are specific to one output path.

**Comment by cippy** [comment]
> Why is an additional command line argument needed here?

Strictly speaking it would not be needed, and in fact it is just more noise for myself when I run tests. I made it because I had understood that other people didn't want the code to continue skipping dummy nuisances with no attached process, and rather wanted the code to throw when it happens. Therefore I wrote the option so that I could instead make the code continue when filtering processes.

**Comment by cippy** [comment]
> Given that this code is specific to the root output I'm kind of inclined to just take this as the moment to start deprecating it rather than introducing more options which are specific to one output path.

So be it, but has anybody ever run with --hdf5 and filtering some processes? While not the standard usage, doing this filtering can be part of several tests, so a similar feature should also exist for the hdf5 version.

**Comment by bendavid** [comment]
Yes I have run tests along these lines and it was working ok (I think just skipping the corresponding nuisances or maybe leaving them in but not affecting any process such that they just stay at the input value and don't affect the results)

If we need to fix something there we of course can/should, but at least then there's only one place to fix things.

**Comment by cippy** [comment]
Ok, but I would need at least that fix that changes the return to continue, otherwise I need to edit my code locally all the times, until the root version is used.
If other people don't use the root version that I agree there is no need to have that new option, it's just noise

**Comment by bendavid** [comment]
Ok yes sure, reopen the pr with just that change and we can merge it then

**Comment by cippy** [comment]
Reopening this now, reverting the new option that was introduced before to allow for some lone LnN systematics not associated to any valid process (it can happen when filtering processes). The option was only affecting a part of the code for the root version, not the hdf5 one, hence it is better to avoid it.

However, this PR still fixes the bug that was making all LnN being skipped as soon as a lone one was found (there was a "return" instead of "continue" inside the loop in the function that prepares all LnN systematics).
So now the code will no longer raise error when a lone LnN is found, and a warning is issued. This was the originally intended behaviour.

**Comment by cippy** [comment]
This PR: https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/PR503/2024_08_02/

Reference run: https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/ReferenceRuns/2024_08_02_75d5ea8/

All identical, also in lowPU (I think I see a few small changes due to rounding in the list of impacts, for some theory nuisances, but I think this is ok, especially because this change only affect the root based fit which is going not to be used anymore at some point)

**Comment by bendavid** [comment]
Wait sorry, why would this make any difference for the low pileup?

The only way this could happen is if somehow a nuisance was added or removed, but this should not be the case according to my understanding of the logic.

We'd better understand what changed here before merging.

**Comment by cippy** [comment]
> Wait sorry, why would this make any difference for the low pileup?
> 
> The only way this could happen is if somehow a nuisance was added or removed, but this should not be the case according to my understanding of the logic.
> 
> We'd better understand what changed here before merging.

Ok, I'll check running local tests, counting the nuisance parameters

**Comment by cippy** [comment]
From CI the low PU didn't use the root version of setupCombine.py, hence the changes we saw cannot be due to this PR, there must have been some intermediate change between reference run and this PR, in particular the setupCombine step show som warning about the ABCD method, and indeed the only differences were found in impacts from fakes (mainly a swapping within the rounding)

**Comment by cippy** [comment]
After merging from the WMass/main the PR and the reference runs are identical, as anticipated. I think we can merge this PR

**Pull request merged**
