### PR TITLE
Updates on QCD background

### PR DESCRIPTION
**Pull request by davidwalter2**
- Set MC bin by bin stat scaling back to 1.125
- Set default smoothing back to 'full'
- Remove O(x^3) parameter variation

### CODE REVIEW

**Comment by bendavid** [comment]
hmm, with the monotonic constraint removed the full smoothing is breaking the nominal plots in the CI again.

maybe we want to add a second version with fakerate smoothing and/or with the monotonic constraint turned back on just for comparison purposes in the low stats ci?

**Comment by davidwalter2** [comment]
> hmm, with the monotonic constraint removed the full smoothing is breaking the nominal plots in the CI again.
> 
> maybe we want to add a second version with fakerate smoothing and/or with the monotonic constraint turned back on just for comparison purposes in the low stats ci?

The hybrid smoothing before looked reasonable, it has the positive constraint for the fakerate. Why not leave this as default for now?

**Comment by bendavid** [comment]
I've launched the high stats CI as well to explicitly confirm it uses the right options for the plots in this case.

**Comment by bendavid** [comment]
*sigh* no the full stats CI did NOT pickup --fakeSmoothingMode full as intended for the plotting.

**Comment by bendavid** [comment]
Ok finally this is working as intended for both the low stats and high stats CI.

**Pull request merged**
