### PR TITLE
Updates of recoil calibration highPU

### PR DESCRIPTION
**Pull request by jeyserma**
- Added calibrations for DeepMETPVRobust and DeepMETPVRobustNoPUPPI
- Updated calibrations for RawPFMET and DeepMETReso (old DeepMET) - for consistency
- Statistical uncertainties defined for all 4 MET definitions (no systematics for now)
- Switched to DeepMETPVRobust as default MET - will change central values of data and MC

### CODE REVIEW

**Comment by davidwalter2** [comment]
Looks good to me, can it be merged?

**Comment by davidwalter2** [comment]
> It should be fine, but I can't see the outcome of the validation - the website seems down? https://cmsmwbot.web.cern.ch/WMassAnalysis/

For me it works, the CI for this PR:
https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/PR429/2024_04_15/
Compared to the reference run:
https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/ReferenceRuns/2024_04_12_98f7547/

**Comment by jeyserma** [comment]
For some reason Chrome gives me "Bad Request", but in Firefox it works.

Anyhow, I compared it with the reference run and things look similar, as expected.

**Comment by davidwalter2** [comment]
> For some reason Chrome gives me "Bad Request", but in Firefox it works.
> 
> Anyhow, I compared it with the reference run and things look similar, as expected.

You can try to remove the cookies for this page and reload

**Pull request merged**
