### PR TITLE
Additions for plotting and nuisance exclusion

### PR DESCRIPTION
**Pull request by kdlong**
- Option to normalise MC to data in plotting
- Some extensions for plotting systematics
- Some special keywords for syst groups to make --exclude and --keep easier to use
- Extend concatenateHists function to merge syst axes for future use in plotting

### CODE REVIEW

**Comment by davidwalter2** [comment]
Do you update wremnants-data intentionally?

**Comment by kdlong** [comment]
I did, yes, to add the new N3LLp correction files. There are other PRs updating to newer versions, not sure if it will cause a conflict

**Comment by davidwalter2** [comment]
We see some differences in the CI, is this expected?
reference: https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/ReferenceRuns/2024_02_09_87700ff/
yours: https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/PR389/2024_02_13/

**Comment by kdlong** [comment]
Ah, good catch. I accidentally committed the dxy cut change. Didn't mean to do that. Will revert.

**Pull request merged**
