### PR TITLE
Additional updates to help prepare HEPData

### PR DESCRIPTION
**Pull request by cippy**

### CODE REVIEW

**Comment by davidwalter2** [comment]
For all the plotting scripts where you create the HepData entry, can you move everything what is within the "if args.saveForHepdata:" block into a separate function in a common file? And Only import ROOT in this common file?

**Comment by cippy** [comment]
> For all the plotting scripts where you create the HepData entry, can you move everything what is within the "if args.saveForHepdata:" block into a separate function in a common file? And Only import ROOT in this common file?

The problem is that different plots requires different information stored, so it is not really feasible to have a single function working for all. This possible function could include different specialisation inside it, but since they would largely rely on the features of the original scripts it would just create a hidden interface that is easy to break. Having it directly in each script where it is needed makes it less error prone

**Comment by davidwalter2** [comment]
Instead of different specifications you can also write multiple functions, even if you can't reuse code I still think it is better to put these blocks into separate functions in a separate file, e.g. a new file in utilities/io_tools for hepdata only. 
The hepdata is very rarely used while the plotting scripts itself are used quite often and also worked on quite often. Reducing the space that the hepdata functionality takes in the plotting scripts will improve readability. I also don't understand why you think it would break or it would be more error prone, I would argue the opposite due to the more modular structure.

**Comment by cippy** [comment]
> Instead of different specifications you can also write multiple functions, even if you can't reuse code I still think it is better to put these blocks into separate functions in a separate file, e.g. a new file in utilities/io_tools for hepdata only. The hepdata is very rarely used while the plotting scripts itself are used quite often and also worked on quite often. Reducing the space that the hepdata functionality takes in the plotting scripts will improve readability. I also don't understand why you think it would break or it would be more error prone, I would argue the opposite due to the more modular structure.

I'll try to make it better.
One of the limitations encountered so far is that what's needed for hepdata necessarily requires some hardcoded pieces of code. For example, in the case of the mass summary plots, that part has to know how many columns you have and how they are labelled, which is not always automatically obtained from the script itself (e.g. the fact that one has PDF uncertainty rather than another uncertainty). So moving everything in another file implies having a function that must know the script where it will be called, and will also need several arguments to get the required information. That's why I thought it is better to keep it directly where it is needed, being just 10 lines.
On the other hand, there is no reason why we have two scripts to make the PDF and Wpt modelling summaries, but this is before doing hepdata. Merging those scripts should probably have larger priority.

**Comment by cippy** [comment]
Last commit doesn't yet include the change discussed before, I'll do something in a next one

**Comment by cippy** [comment]
Last commit should do what you asked, the text of the commit is not so informative because I overwrote it by mistake after fixing pylint stuff, but basically it adds a new script to collect hepdata utility functions, and edits the other scripts which were using them

**Comment by davidwalter2** [comment]
> Last commit should do what you asked, the text of the commit is not so informative because I overwrote it by mistake after fixing pylint stuff, but basically it adds a new script to collect hepdata utility functions, and edits the other scripts which were using them

Thank you! I think it is much better. From my side I'm happy to merge it once the CI has passed and looks good

**Pull request merged**
