### PR TITLE
Alternate derivation and usage of veto SF for W analysis

### PR DESCRIPTION
**Pull request by cippy**
Choice of previous or newer veto SF is customisable, and the default keeps the old behaviour.
The details concerning the difference between the two schemes can be discussed elsewhere, e.g. in the working group meeting. 

There are also some possible improvements in common functions to apply the veto SF in the histmaker.
In principle there should be no change with the respect to the reference runs, but some minor effects might appear because of these updates, in which case we should agree on whether we want to revert them or keep them (if they are more correct).

This PR also requires an update in wremnants-data to use the new files (when chosen to do so). Some of these are intermediate utility files used to create the file SF histograms (they are used by some python plotting scripts which also finally produce them).

Technical details: at the moment there is some duplication of the code to prepare the veto SF histograms and configure the helpers. There are some new *_TEST.(py|h) scripts which can be renamed or possibly merged with the others in a next iteration.  However, right now the duplicated C++ helper classes have been given the same name (so the .py configuration scripts are not imported together, or compiling would fail because of duplicated definitions) because in the future one could converge to a single implementation.

### CODE REVIEW

**Comment by cippy** [comment]
In the last commit I am implementing the validation of veto SF using the WLike histmaker (activated through dedicated new option, but currently only for the new veto SF because for the older one I am not sure we store the SF anywhere at the moment). 
To facilitate this validation, I am updating some of the functions to apply scale factors or their variations, to allow of some customisation of the name of input variables needed for the corresponding helpers, while also allowing calling the same functions multiple times without overriding the output histogram they would produce (it just needs a unique tag in the name which can be specified as function argument).

I need to fix the conflicts with the submodule now, I think I know how to do it but I need to some time to make sure I do things right, it's easy to mess things up

**Comment by cippy** [comment]
For now I reverted the change in the submodule commit, CI might still work because it will not use the new files by default. I'll then try to fix this submodule issue by creating a fresh new PR to wremnants-data with clean history.

**Comment by cippy** [comment]
Why does it keep conflicting ? The commit report on this PR says that I am moving the submodule "from 8e1c5f to f9d103", but before moving the commit I had checked out [7eeb03a](https://github.com/WMass/WRemnants/blob/main/wremnants-data) to ensure I update it from there. Perhaps the gitlab PR has a different history ? Namely I should open the new PR from that same commit 7eeb03a rather than the current master ?

**Comment by bendavid** [comment]
Does --useGlobalOrTrackerVeto still work with this PR? (at least while using the old veto scale factors and uncertainties)

**Comment by cippy** [comment]
Ok, it was enough to to again the usual "git pull --recurse-submodules upstream main". When I was using the submodule commit pointing to the first PR to wremnants-data (https://gitlab.cern.ch/cms-wmass/wremnants-data/-/merge_requests/68) it was indeed giving conflicts, but with the new PR (https://gitlab.cern.ch/cms-wmass/wremnants-data/-/merge_requests/70) created from a clean branch it was able to merge the history by itself. Let's wait for CI now

**Comment by cippy** [comment]
Reference run: https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/ReferenceRuns/2024_07_25_9b78f87/

This PR: https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/PR500/2024_07_25/

No difference seen neither for W nor Wlike (for single nuisance impacts in the Wmass case two lines are swapped, but within rounding the numbers are exactly the same).
This is expected: in fact even with default veto SF some tiny changes could have been possible because of some improvements in the functions used to pick the second gen muon to apply the veto SF (selecting the one matched to the reconstructed muon based on the minimum DR, rather than the first satisfying the geometrical matching, but since the gen muons are most often in opposite phi regions there will be only one gen muon matched to the reco), but the resulting effect was in any case expected to be negligible.

I actually have some additional commits to push, which allows the Wlike to be run filling the histograms with the nonTriggering muon (which as a particular use case could be selected with the veto selection, thus allowing one to check the prefit uncertainty bands as obtained from combinetf as a function of the loosely selected muon pt/eta). 
However this is only currently implemented using the new veto SF, because I don't think we currently store the veto SF for the default method (only antiveto SF are available), so it should also not change the results of CI.
It might be worth doing all in this PR directly, also for the purpose of reviewing the whole picture

**Comment by cippy** [comment]
The updated CI results with the last commit are still in the same folder as before, and I see no changes with respect to the same reference run (modulo the previously mentioned swapping of a couple of impacts for 2 nuisance parameters in the Wmass fit).

This should be ready for review and possibly merge, but there is no urgency.

**Comment by bendavid** [comment]
Please modify this to NOT have duplicated C++ class names.

This can cause huge confusion/debugging pain in case the wrong header gets imported somehow etc.

**Comment by cippy** [comment]
> Please modify this to NOT have duplicated C++ class names.
> 
> This can cause huge confusion/debugging pain in case the wrong header gets imported somehow etc.

Agreed, it was supposed to be temporary indeed. The most annoying part was having to rename all classes, with the possibility that eventually one header would have been removed.

In principle my new header can also digest the older SF, but this would currently imply a potential small change in the yields, because Davide was setting the antiveto SF to 1 if the moused to apply them has pt > 65 GeV, which is the highest pt value used to compute them, while I am just assigning the closest SF value (as we do for all other SF when we read the overflow pt). I think the latter logic is better defined, but I didn't want to introduce a change in CI (it might be invisible, though)

**Comment by cippy** [comment]
I renamed the classes for the new veto to be distinct from the previous ones, but for this round we still have two independent classes, one specific for each veto strategy. Combining them right now is a little less straightforward because of how the uncertainties for stat are defined, which makes it not very clean to use the same class. 

It can be possibly improved further in the future, and as a first attempt I started modifying the .py and .h for the default veto helper, to be more centred around boost histograms. In particular, I am passing a single histograms with charge as an axis (there were two histograms before, one per charge), and I removed the condition on the overflows eta-pt bin inside the helper, so that we can allow for high pt events without offsetting the SF to one (for low pt and eta edges there is no problem with removing the cuts, since the muon used to read the bin is already inside acceptance, and if it doesn't exist the helper already returns SF=1)

**Comment by bendavid** [comment]
Thanks, can you edit the PR description to reflect the last updates?  (ie removing the part about duplicated C++ class names etc)

**Comment by cippy** [comment]
I modified the initial message to reflect the latest changes

**Pull request merged**
