### PR TITLE
improvements for plotting

### PR DESCRIPTION
**Pull request by tyjyang**

### CODE REVIEW

**Comment by kdlong** [comment]
I'm a little confused here. At some point the matplotlib auto tick setting got messed up, and the fix_axes was my attempt to recover it. It doesn't always get things like the number of decimal places optimal, but at least restores some of the auto setting of bins in a reasonable way. So this undoes that and instead requires the user to pass in numbers each time? Do you want to fall back to the auto setting if no values are passed?

**Comment by tyjyang** [comment]
The reason for setting the tick labels manually is because the auto labeling doesn't work in some cases. For example, when I plot histograms with bins from 0.999 to 1.001, all ticks are labeled as 1.

It wouldn't necessarily require the user to manually pass in the decimal place, as the default for `x_ticks_ndp` is `None`; and when this is the case, labels will be set automatically.

**Comment by tyjyang** [comment]
ah sorry I didn't realize that I deleted `fix_axes(ax1, ax2)`, will add that line back in

**Comment by kdlong** [comment]
Happy to merge this, but you might want to take a look at improving this function as well: https://github.com/WMass/WRemnants/blob/93e25e52e01c795c03ac283a2a1eab215a480da4/wremnants/plot_tools.py#L221-L224

It would be better to have this handled automatic vs. having to set manually, at least for the majority of cases (I have no problem with it being possible to set manually, but would rather not have to do it for every plot)

**Pull request merged**
