### PR TITLE
Support alphaS fit

### PR DESCRIPTION
**Pull request by davidwalter2**
- Implement options to fit alphaS (and sin2ThetaW) as POI
- Add ptll alphaS asimov fit to CI; remove ptll fit
- fix small issue in impact plot where in a combination of arguments the total impact in the grouped impacts was not shown

### CODE REVIEW

**Comment by bendavid** [comment]
Presumably the alphaS fit in the CI is expected only?

**Comment by davidwalter2** [comment]
> Presumably the alphaS fit in the CI is expected only?

yes

**Comment by davidwalter2** [comment]
This would be ready for review/ merge:
this PR: https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/PR556/2024_11_04/
reference: https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/ReferenceRuns/2024_11_01_803c297/

**Comment by kdlong** [comment]
We should probably double check the symmetry of the alpha_s variation, and we also might as well add the width fit to the CI as well, but as a technical implementation, this is worth merging

**Pull request merged**
