### PR TITLE
refactoring muon calibration and validation functions in mW histmaker; muonScale nuisances for tau processes

### PR DESCRIPTION
**Pull request by tyjyang**
- separating functions that are integral to the default muon calibration procedure, and functions that validate the procedure
- tested that the mw histmaker works with `args.validationHists` enabled
- make mW combine script read non-closure nuisance scheme from the hdf5 metainfo

### CODE REVIEW

**Comment by kdlong** [comment]
I'm not sure I really understand the difference between calibration and validation here, but I don't think it's a big deal. It looks ok to me

**Comment by tyjyang** [comment]
> I'm not sure I really understand the difference between calibration and validation here, but I don't think it's a big deal. It looks ok to me

Yeah it's nothing major, just to de-clump `muon-calibration.py` by moving some functions such as generating alternative muon kinematics for validation studies to another file.
What I have in mind is to separate the nominal calibration workflow for our final analysis results from various other functions that are there to just validate this workflow.

**Comment by kdlong** [comment]
Is it ready to merge from your side?

**Comment by tyjyang** [comment]
@kdlong yes

**Comment by kdlong** [comment]
main ==> https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/PR244/2023_06
this PR ==> https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/PR235/2023_06

It looks like things are basically unchanged to me.

**Comment by tyjyang** [comment]
> main ==> https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/PR244/2023_06 this PR ==> https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/PR235/2023_06
> 
> It looks like things are basically unchanged to me.

Well the muonScale impact changed from 2.08 to 2.33 with the nuisances added for the taus.

**Pull request merged**
