### PR TITLE
implement altBkg effSyst (only tracking for now)

### PR DESCRIPTION
**Pull request by rubenforti**
Added the systematic related to alternative model of background for the tracking efficiency step.

Before the merge, the new root file "allSmooth_GtoHout_vtxAgnIso_altBkg.root" has to be present in "wremnants-data": another PR has been opened to do that, and it has to be closed before this one.

### CODE REVIEW

**Comment by bendavid** [comment]
Ok the needed file has been added to wremnants-data

**Comment by bendavid** [comment]
This has conflicts now (I think related to https://github.com/WMass/WRemnants/pull/415 which was just merged)

**Comment by dbruschi** [comment]
I was trying to open a PR to @rubenforti 's repository with the fixed conflicts, but then it conflicts with his repository (but not with WMass:main), so I guess he has to do it. The reason the conflicts are present is because both https://github.com/WMass/WRemnants/pull/415 and this PR modify the same lines, in particular Ruben's lines to implement the altBkgSyst are my lines to implement the veto, it should suffice then to put Ruben's lines just before mine, or the other way around.

**Comment by bendavid** [comment]
Some test failures

**Comment by rubenforti** [comment]
Now the errors should have been fixed by Marco

**Comment by dbruschi** [comment]
I think an append is missing: https://github.com/WMass/WRemnants/pull/440/commits/4572cd15deef18651cd8e4d8cb3630ed03bd41a4#diff-307e1a9fe2ccc1e9e6ed0aa754e70347cb27d7653aa9827c2ca4ecb1c7ca5dfdL618

**Comment by cippy** [comment]
I compared the PR validationto to the one of PR #415 from Davide, and the plots are exactly the same. The impacts are slightly changed for this PR since it adds new nuisance parameters for tracking effSyst (note that we also added the new systematics to the Z histmakers, so their impacts are expected to change as well).

Anyway, I would invite other people to confirm my findings

**Comment by davidwalter2** [comment]
It looks all right to me, increasing mW uncertainty from 19 to 19.2 in the low stat CI, for me it's fine merging now.

**Pull request merged**
