### PR TITLE
Update smoothed 3D scale factors to use larger range of uT

### PR DESCRIPTION
**Pull request by kdlong**
Taken from the open PR of @cippy so we have a better record of the standalone impact. Marco let me know if this isn't the right description of the changes.

### CODE REVIEW

**Comment by cippy** [comment]
I just changed the title to correct mT -> uT
Basically the new file has SF up to 100 GeV in recoil uT, it was 30 before, so we can expect some slight changes in signal and background yields (they are probably not going to be visible from the data/MC plot, since we are talking about at most 0.5% change localised in specific eta-pt regions, mainly at low pt)

**Comment by kdlong** [comment]
Oops thanks. Should I run high stats validation or do you think this is good enough?

**Comment by kdlong** [comment]
This PR: https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/PR266/2023_08_08
Reference: https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/PR262/2023_08_07

--> Reference should be the PR that was just merged before it, not this morning's run

**Comment by kdlong** [comment]
The changes look tiny to me. @cippy should we merge?

**Comment by cippy** [comment]
Hi, yes, the plots look reasonable, both the shapes and the impacts. I noticed a large change for the luminosity in W impact groups, but since this is not with the full stat it is not impossible, the new SF modify a bit the shape of the background vs pt, so it could be just a different constrain or correlation with other things.

I would say you can merge

**Comment by kdlong** [comment]
Should I run it with full stats to double check, or are you pretty confident?

**Comment by cippy** [comment]
Maybe let's run the full stat just to be sure, it should only take 1 hour or so

**Comment by kdlong** [comment]
High stats (W still running): https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/PRsmooth3DSF/2023_08_09/
Compare to: https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/PRlambdaNP/2023_08_07/

**Comment by kdlong** [comment]
Lumi change looks reasonable to me. Merging

**Pull request merged**
