### PR TITLE
Add theory agnostic analysis with POI as NOI to CI

### PR DESCRIPTION
**Pull request by cippy**
Testing if it works. For the histogram it reuses the same file as for the traditional analysis, which is augmented with the yieldsTheoryAgnostic histogram. Then the setupCombine and fit parts are simply duplicated from the standard wmass workflow.

No change should be expected for the traditional analysis in the impacts and other plots. A new plot is added for the impact from the theory agnostic fit (but it is possible the fit doesn't even converge when using a small fraction of the MC stat, to be seen).

### CODE REVIEW

**Comment by cippy** [comment]
> I thought we discussed that --theoryAgnostic --poiAsNoi should effectively become the default for the histmaker step in this case.

Yes, but --poiAsNoi is also used for unfolding, so unless even the unfolding is only expected to run with it from now on it might be better to keep it selectable (or we implement the opposite option to use real POIs when needed, but then we need to swap the behaviour in several places)

**Comment by bendavid** [comment]
The workflow runs and the impact plots are produced.  There's something wrong with the plotting of the grouped impacts though, in that the norm uncertainties appear not to be included.

It also looks like the full set of theory uncertainties is included in the theory agnostic fit (in addition to the norm nuisances), but I think this is ok for the moment (and maybe even desirable but that is another discussion)

**Comment by bendavid** [comment]
I guess we want a command line option for the card tool to skip the qcd uncertainties (non-perturbative, theory nuisance parameters,  QCD scales and PDF/alphaS) since these are the ones which cover in principle the same degrees of freedom as the theory agnostic norm parameters.

**Comment by davidwalter2** [comment]
> The workflow runs and the impact plots are produced. There's something wrong with the plotting of the grouped impacts though, in that the norm uncertainties appear not to be included.
> 
> It also looks like the full set of theory uncertainties is included in the theory agnostic fit (in addition to the norm nuisances), but I think this is ok for the moment (and maybe even desirable but that is another discussion)

For the grouped impacts only the ones from [this dictionary](https://github.com/WMass/WRemnants/blob/main/utilities/styles/styles.py#L77-L107) are drawn to avoid having them multiple times (nuisances can appear in multiple groups and subgroups). So you need to add the group namess for the theory agnostic nuisances, I think "yieldsTheoryAgnostic_OOA_yV" and "yieldsTheoryAgnostic_OOA_ptVyV", in that dictionary.

**Comment by bendavid** [comment]
For the command line options  --theoryAgnostic --poiAsNoi yah I agree this is problematic since poiAsNoi should be the default for the theoryAgnostic but not for the unfolding

Maybe there is a smarter way to do it with argparse

**Comment by davidwalter2** [comment]
> For the command line options --theoryAgnostic --poiAsNoi yah I agree this is problematic since poiAsNoi should be the default for the theoryAgnostic but not for the unfolding
> 
> Maybe there is a smarter way to do it with argparse

We can use the "set_parser_default" in case --TheoryAgnostic is given. Similar to here:
https://github.com/WMass/WRemnants/blob/main/scripts/histmakers/mw_with_mu_eta_pt.py#L46-L47

**Comment by cippy** [comment]
> > For the command line options --theoryAgnostic --poiAsNoi yah I agree this is problematic since poiAsNoi should be the default for the theoryAgnostic but not for the unfolding
> > Maybe there is a smarter way to do it with argparse
> 
> We can use the "set_parser_default" in case --TheoryAgnostic is given. Similar to here: https://github.com/WMass/WRemnants/blob/main/scripts/histmakers/mw_with_mu_eta_pt.py#L46-L47
> 
> ```
> if args.theoryAgnostic:
>     parser = common.set_parser_default(parser, "poiAsNoi", True)
> ```

sure, but then these options need to be used also in setupCombine in a consistent way, so I have the impression that an explicit usage saves us a lot of possible mistakes.

**Comment by cippy** [comment]
If the pdfs and qcd scales are removed from the theory agnostic fit, what do we do for the out of acceptance? Right now since the OOA is not treated as an independent process with its own histogram we can't have pdfs applied only to it for example. This is because the pdfs are actually applied on the nominal histogram, which has no information about what is in acceptance or out of acceptance (it doesn't have the gen bins).

Perhaps if this is needed (to use theory uncertainties only on the OOA), we can re-implement the splitting into a separate process, which can possible have all its gen bins too to be more flexible in defining variations on it. Since the OOA process still belongs to the Wmunu group, the nominal histogram and all other systs can still be defined merging IA and OOA together at cardtool level into a single process when doing the traditional fit (this is how it was originally implemented, and simply allowing to keep them split for the theory agnostic when requested).

**Comment by bendavid** [comment]
If the OOA has a norm uncertainty then arguably the QCD/PDF uncertainties can also be removed from the OOA.

**Comment by cippy** [comment]
This is a plot I got from a test local run with 1:1 data/MC stat: https://mciprian.web.cern.ch/mciprian/WMassAnalysis/fromMyWremnants/fitResults/theoryAgnostic_poiAsNoi/09Nov2023/WMass_eta_pt_charge/makeImpactsOnMW/impactsOnMw_compare_noQCDtheorySyst.pdf

It compares the impacts with and without PDF/QCD theory systs. It was mainly to see if the numbers are still compatible with what we used to get before (note that here I used a random |yW|/ptW binning, 5 uniform bins each from 0 to 2.5 and 0 to 50 GeV, so it's not the same default binning as the code, which uses the optimised one from Elisabetta).

Unless there are counter objections, I'll update the PR to automatically remove PDFs and QCD uncertainties for the theory agnostic, and fix CI to make the proper impact plot

**Comment by bendavid** [comment]
No no let's keep the QCD/PDF uncertainties there by default, but just add a command line option to remove them.

**Comment by emanca** [comment]
Can we refrain from discussing concepts in the PRs and use the other channels (e.g. meetings, Mattermost) for that?

**Comment by cippy** [comment]
In the last commit I modify the combine_theory_helper to facilitate customization of the samples to use. This is needed to allow removing theory systs from signal (but keeping them on Z) in the theory agnostic analysis.

This is still WIP since it is removing the uncertainties also from Wtaunu despite it not having the normXsec uncertainties. The main problem is that the interface to set the theory nuisances uses different sample groups in different places, and it is quite hard to customise them in a flexible way (would need to be able to specify a group for each systematic source).

**Comment by cippy** [comment]
I am not sure I understand why CI fails for lowPU on the W this time. 
It seems it doesn't find "single_v_nonsig_samples" in card_tool.procGroups, and thus it triggers the error in the initialisation of combine_theory_helper, but in fact this group was being passed also before, just that it was not being explicitly checked. 
So what was actually happening? Were we passing those processes (the Z samples) assuming to have them and then they were not found and consequently skipped with no further notice ?

**Comment by cippy** [comment]
I think this is ready for review and merge when CI ends, if successful

**Comment by bendavid** [comment]
Wtau should probably also be treated as signal, but ok that can be done later.

**Pull request merged**
