### PR TITLE
Decorrelate effSyst nuisances in 48 eta bins, and restore symmetric variations

### PR DESCRIPTION
**Pull request by cippy**
In addition to the title, there are changes in some plotting scripts which don't affect the analysis.
There is also a first version of a new script to prepare the 2D smoothing for isolation/trigger scale factors

It also includes a minor optimisation of the functions to Divide/Multiply boost histograms, adding the createNew argument as in other functions.

The only real files which have changed are:
**scripts/combine/setupCombineWMass.py** (change of settings for effSyst)
**wremnants/CardTool.py** (bug fix for decorrelated nuisance)
**utilities/boostHistHelpers.py** (minor changes for DivideHists function)

### CODE REVIEW

**Comment by cippy** [comment]
This fails for the dilepton analysis because the decorrelation is done at CardTool level and expected histograms with eta-pt-charge. Even when the charge is not present, it requires that the template observables are the variables you want to decorrelate into, which is not the case here since the templates are pull-yll.

So this has to be done at histmaker level regardless.
Also for Wlike the current approach is only an approximation (albeit it might be an excellent one), since it neglects the effect of the second lepton.

So this has to be changed

**Comment by cippy** [comment]
The last commits implement the decorrelation at histmaker level. The logic currently works only versus eta, but in principle it could be easily extended into an eta-pt-charge one. For now we only expect to decorrelate versus eta anyway.

This has required changing the helper class for the nominal and syst variations, adding a template argument represents the number of systematic variations. At the moment they are 1+N, because the inclusive global variation is kept along the N eta-decorrelated ones.

**wremnants/include/muon_efficiencies_smooth.h** and **wremnants/muon_efficiencies_smooth.py** have been modified. At some point the changes should be propagated also to the helpers for the binned scale factors, for consistency if we ever need to run those as well as a check, but not urgent for now.

**scripts/combine/setupCombineWMass.py** has been updated to use this new logic, instead of the decorrelation at cardTool level

**Comment by davidwalter2** [comment]
Is this ready for merge?

**Comment by cippy** [comment]
Yes, it is ready
Let me also point out that among other things I modified the name of the effStat nuisances from effStatSmooth_blah to effStat_blah, to avoid having too long names (also because it is clear we will never use the binned SF for any serious purpose anymore)

**Pull request merged**
