### PR TITLE
force lumi to any value to normalize MC 

### PR DESCRIPTION
**Pull request by cippy**
Useful when data process doesn't exist in the output of a histmaker (the default normalises MC to 1/fb), but even when data exist one might prefer to scale MC to some predefined value in plotting scripts.

### CODE REVIEW

**Comment by kdlong** [comment]
Is this really the way you want to do this? I added an option for this in the matplotlib plotting scrips but I didn't touch the values in data groups, it's just applying a scaling on the hists themselves.

https://github.com/WMass/WRemnants/blob/main/wremnants/plot_tools.py#L210-L217

**Comment by kdlong** [comment]
There is also no reason that you need to introduce a new variable. Just do

```python
groups = Datagroups(fname)
groups.lumi = yourlumi
```
Actually the way we are using get and set functions is not really pythonic, it's more C style. Setting the variable directly is perfectly fine

**Comment by cippy** [comment]
> Is this really the way you want to do this? I added an option for this in the matplotlib plotting scrips but I didn't touch the values in data groups, it's just applying a scaling on the hists themselves.
> 
> https://github.com/WMass/WRemnants/blob/main/wremnants/plot_tools.py#L210-L217

Yeah it could be done at that level scaling the histograms directly, I was just not sure if for any reason it was better to fix the lumi normalisation directly in the very core of datagroups. It would matter for the fakes for instance, but for them you need data anyway. 

In fact, the new argument I added could have a default value of 1/fb, and then the code would warn you as it was doing before. However, in the current way you can use it to override the actual luminosity in data even when data are present, while to achieve the same at histogram level you would need to know the original lumi in data to rescale accordingly (I guess this can be obtained, but you still need two more lines of code)

**Comment by cippy** [comment]
> There is also no reason that you need to introduce a new variable. Just do
> 
> ```python
> groups = Datagroups(fname)
> groups.lumi = yourlumi
> ```
> 
> Actually the way we are using get and set functions is not really pythonic, it's more C style. Setting the variable directly is perfectly fine

ok, I guess this would work as well, but if this happens with the constructor it is really the same code with one less line. Other than that, I can do it as you suggest if there is a particular preference for that.

**Comment by kdlong** [comment]
The reason is to avoid adding more arguments that only serve a very narrow purpose. I suggest doing it this way indeed.

**Comment by kdlong** [comment]
And then there is no need for an argument, anyone doing this should know what they're doing

**Comment by cippy** [comment]
Done, so eventually the only change is in a plotting script, in principle CI is no longer needed

**Pull request merged**
