### PR TITLE
Updating plotting scripts and other miscellanea

### PR DESCRIPTION
**Pull request by cippy**
Opening a big PR with lots of updates for plotting scripts. There are some changes relevant for the analysis, but for them I'll open another PR in a few minutes.

### CODE REVIEW

**Comment by cippy** [comment]
This is ready to go whenever you feel like, we should have already verified that it doesn't change anything for the analysis.

**Note**: it could have potentially changed something for the veto uncertainty because it defines the gen eta-pt acceptance using gen pT > 15 (the default was still 0), but in practice it doesn't because the veto helpers apply SF=1 when the gen pt is outside the histogram pt range, which starts from 15 GeV. However I think it is better to explicitly define the get Pt acceptance as the pt threshold for the veto, and in fact the two thresholds could be tied up

**Comment by bendavid** [comment]
Can you give the PR a more meaningful name?

**Comment by cippy** [comment]
Done, sorry

**Comment by cippy** [comment]
CI apparently failed for some file issue at the unfolding/w-like workflow, very annoying. I'll try rerunning that one

**Comment by cippy** [comment]
Now it failed because it couldn't create the output path, but I think it is just because the script doesn't create subfolders when the main one already exists, since it just checks the main one. I had modified the script to always recreate folders, but I didn't set it as default to maintain the previous behaviour. It seems a good moment to do it

**Comment by cippy** [comment]
This PR:
https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/PR457/2024_05_27/

Reference run:
https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/ReferenceRuns/2024_05_30_c477494/

They look the same, can we merge this one ?

**Pull request merged**
