### PR TITLE
Add photon-induced contributions as background

### PR DESCRIPTION
**Pull request by mseidel42**
Photon-induced contributions, <0.1% in both W and Z selections

### CODE REVIEW

**Comment by davidwalter2** [comment]
Should we include a normalization uncertainty here?
https://github.com/WMass/WRemnants/blob/main/scripts/combine/setupCombine.py#L589-L602

**Comment by mseidel42** [comment]
Ok :+1: But do I see correctly that there is no uncertainty on "Other" for the W fit yet?

**Comment by davidwalter2** [comment]
> Ok 👍 But do I see correctly that there is no uncertainty on "Other" for the W fit yet?

There is a 15% uncertainty:
```
 cardTool.addLnNSystematic("CMS_background", processes=["Other"], size=1.15, group="CMS_background")
 ```

**Comment by bendavid** [comment]
Sorry which 15% uncertainty are you talking about?

**Comment by cippy** [comment]
For the W case we don't have the "Other" background, we keep Top and Diboson separate, each one with its own LnN uncertainty for the cross section [0]. We should have independent numbers for each top/diboson subprocess, yet we chose a possibly conservative single value for the sum. In principle we should allow for shape variations, but it's most likely irrelevant considering that all experimental uncertainties are already applied to them. The 15% for the "Other" background (which is Top+Diboson) in the Wlike or dilepton case comes from those numbers more or less.

[0] https://github.com/WMass/WRemnants/blob/main/scripts/combine/setupCombine.py#L632-L633

**Comment by bendavid** [comment]
Ok so there's no 15 percent uncertainty on the single Z production anywhere then.

**Pull request merged**
