### PR TITLE
Add mb and mc quark mass variations to fit

### PR DESCRIPTION
**Pull request by kdlong**
- Add variations of mb and mc from the PDF using MiNNLO and SCETlib+DYTurbo. Currently the SCETlib+DYTurbo variation only works when MSHT20 is the central PDF set. This could of course be changed, but I don't think it's worth it: MiNNLO gives a very similar answer and the distributions are quite similar (0.5-0.6 MeV impact on mW)
- Fix theory corr pre-processing from adding additional vars to non-scale hists
- Separate theory unc CL arg into --theoryCorr and --addTheoryCorr. This makes it a lot easier to change the corrections while keeping the EW corrs needed for the fit

### CODE REVIEW

**Comment by davidwalter2** [comment]
Where is the updated wremnants-data pointing to?

**Comment by kdlong** [comment]
> Where is the updated wremnants-data pointing to?

IT is pointing to the MR commit right now, should be ok once it's merged

**Comment by kdlong** [comment]
Nope, you were right, I hadn't opened the MR yet. But it worked since it was a branch on the main repo. Now made: https://gitlab.cern.ch/cms-wmass/wremnants-data/-/merge_requests/44

**Comment by davidwalter2** [comment]
I think there is still a mismatch with the wremnants-data, the commit doesn't show up in the main branch so if we would merge I think the wremnants-data would point to the branch CT18Zvars, can you try to make it point to 507d4ecc?

**Pull request merged**
