### PR TITLE
Use SCETlib alphas unc by default 

### PR DESCRIPTION
**Pull request by bendavid**
plus minor fix to gen binning and small plotting script changes

This is a more minimal version of https://github.com/WMass/WRemnants/pull/454 (and replaces it for the moment)

### CODE REVIEW

**Comment by bendavid** [comment]
In the CI there is no change in data or MC as expected, and for the impacts, a small change in the pT modelling impact, which is probably reasonable since alphaS has some interplay here.

I will launch high stats CI in any case.

@kdlong one other thing is that it looks like "0" on the axis scale of all the plots is now "0.0" is this expected/desirable?

**Comment by kdlong** [comment]
It's the reverse isn't it? I found it annoying that it would go to 0.0 after all other labels were integers

**Comment by bendavid** [comment]
Ah yes you're right sorry.  Ok I agree this makes sense then.

**Comment by bendavid** [comment]
High stats CI also looks sensible.

**Pull request merged**
