### PR TITLE
Combined low pu fit

### PR DESCRIPTION
**Pull request by kdlong**
Include Jan's changes from #83

Also restructure some pieces of combine script and add new (simple) script to run both high and low PU (currently only W-like) for combined fit

### CODE REVIEW

**Comment by cippy** [comment]
In the histMakers you define the axis axis_eta_mT from -2.4 to 2.4, but it seems you fill it using |eta|.

The rest looks ok

**Comment by kdlong** [comment]
> In the histMakers you define the axis axis_eta_mT from -2.4 to 2.4, but it seems you fill it using |eta|.
> 
> The rest looks ok

@jeyserma

**Comment by jeyserma** [comment]
The eta dependency on the mT will be removed in the next PR, it was introduced for some testing purposes to see the constraining power on the PDFs.

**Comment by kdlong** [comment]
Ok will merge and make updates later in that case.

**Pull request merged**
