### PR TITLE
Scale resumTNP nuisances in CardTool

### PR DESCRIPTION
**Pull request by cippy**
There was already option --scaleTNP to achieve that, but it was not propagated to the datacards. This PR implemented that.

The only relevant files that are modified are:
- **scripts/combine/setupCombineWMass.py**
- **wremnants/combine_theory_helper.py**

The rest is just a set of plotting scripts that don't affect the main analysis.
I checked that the scaling factor is correctly propagated to the datacards for the mW fit (default is 1, namely no scaling).

### CODE REVIEW

**Comment by cippy** [comment]
Scaling TNP by 5 does not apparently modify the total uncertainty in a visible way within rounding precision. 
The uncertainty from group resumTNP increases from 0.2 to 0.6 MeV, so there is an effect within that specific group, although it seems that it is eventually offset by group resumNonpert which is reduced by half.

See comparison of impacts here:
https://mciprian.web.cern.ch/mciprian/WMassAnalysis/fromMyWremnants/fitResults/30August2023/deepMET/makeImpactsOnMW/impactsOnMw_Asimov_compareScaleTNPby5.pdf

**Comment by cippy** [comment]
This apparently failed on the copy-clean step, all the rest was goo

**Comment by bendavid** [comment]
Does this PR make the default scaling 5 as previously discussed?  (Even if the actual numbers don't change much there are some arguments for doing so)

**Comment by bendavid** [comment]
The failure was of course from the xrdcp at the end.  I logged in as cmsmwbot and this alone seems to fix the problem, so probably the kerberos ticket was just expired.

TBD if we can find a way to persist this for longer.

**Comment by cippy** [comment]
> Does this PR make the default scaling 5 as previously discussed? (Even if the actual numbers don't change much there are some arguments for doing so)

It wasn't doing it, but I've just added one commit to do it now.

**Comment by kdlong** [comment]
So #284 implements the same thing but using the scale x5 variations actually produced from SCETlib. I double checked and it's very similar.

It's ok to merge this if you need it now, but it will cause some merge conflicts with #284

**Pull request merged**
