### PR TITLE
Fix tracking alt bkg systematics

### PR DESCRIPTION
**Pull request by cippy**
Fixing the helper, and updating setupCombine.py to use again this systematics.
I am slightly changing the name of groups for the veto nuisances to facilitate gathering later on, and also adding a group that includes all efficiency systematics (both stat and syst together, also with veto).

I am including a few minor changes also in the histmakers for W and Z to add some utility plots (although this mainly relate to another PR which will add some scripts to make plots with them)

### CODE REVIEW

**Comment by bendavid** [comment]
This has conflicts to resolve now.

**Comment by bendavid** [comment]
Merging this is on hold until the unblinding-in-ci is done in order to not change the results.

**Comment by bendavid** [comment]
In the CI there is no change in the data/mc as expected, and some changes in the impacts.  In the limited stats ci the impact of efficiency systematics only decreases from 6.00 to 5.98MeV whereas I would have expected a bigger change (but maybe it's not possible to see in the limited stats case)

Marco did you run the impacts already with nominal/full stats and confirm that the behaviour makes sense?

**Comment by cippy** [comment]
> In the CI there is no change in the data/mc as expected, and some changes in the impacts. In the limited stats ci the impact of efficiency systematics only decreases from 6.00 to 5.98MeV whereas I would have expected a bigger change (but maybe it's not possible to see in the limited stats case)
> 
> Marco did you run the impacts already with nominal/full stats and confirm that the behaviour makes sense?

Not yet, mainly because it took until this late morning to make the histograms, I am basically trying to run the fit now

**Comment by cippy** [comment]
Alright, this seems to make sense again to me

**Comment by bendavid** [comment]
Marco I deleted your last comment because I don't think we want the full impacts in the public repo.

**Comment by cippy** [comment]
> Marco I deleted your last comment because I don't think we want the full impacts in the public repo.

ops, my bad, I didn't think about it

**Comment by bendavid** [comment]
CI and tagging of the dilepton unblinding is sorted now so I'm merging this.

**Pull request merged**
