### PR TITLE
Add new systematic uncertainty for reco SF from alternate background model (and slightly update tracking's one) 

### PR DESCRIPTION
**Pull request by cippy**
This PR requires updating the submodule after merging https://gitlab.cern.ch/cms-wmass/wremnants-data/-/merge_requests/67

It add a new systematic uncertainty for reco SF, using the same code already developed time ago for tracking. The impact of this new systematic uncertainty is 0.6 MeV on mW on its own, which modifies the grouped impact of muon SF from about 2.5 to ~2.6 MeV, and the corresponding effect on the total uncertainty should be negligible. 

The uncertainty for tracking is also going to be updated once the submodule is merged. This was needed because the current uncertainty had been evaluated with respect to a refined set of nominal SF, with some improvements in the treatment of the signal MC template, rather than with respect to the actual SF in WRemnants. However, this is a minor change, the impact for the tracking altBkg systematic was found to change from 0.6 to 0.7 MeV, with negligible effect on the total uncertainty or even on the impact of only the muon SF.

### CODE REVIEW

**Comment by bendavid** [comment]
From the CI this looks like it leads to a small change in the nominal data/mc ratio, for both W and Z.  Is it expected?

**Comment by cippy** [comment]
This PR doesn't really seem to touch anything that would modify the central weights, but the change from CI is quite big. I'll make the comparison in full stat from my local test, I was not expecting the central value to change at all.

**Comment by cippy** [comment]
> This PR doesn't really seem to touch anything that would modify the central weights, but the change from CI is quite big. I'll make the comparison in full stat from my local test, I was not expecting the central value to change at all.

From my local tests I see the exact same histograms. Are we sure the submodule update is being picked correctly by CI in spite of the non merged PR ? It still shouldn't touch the central values, though, but at this point I am not sure what's going on

**Comment by cippy** [comment]
> > This PR doesn't really seem to touch anything that would modify the central weights, but the change from CI is quite big. I'll make the comparison in full stat from my local test, I was not expecting the central value to change at all.
> 
> From my local tests I see the exact same histograms. Are we sure the submodule update is being picked correctly by CI in spite of the non merged PR ? It still shouldn't touch the central values, though, but at this point I am not sure what's going on

Small correction, I was comparing PR498 instead of PR497 (this one), but there is still a difference as you pointed out. Could it be that by updating my local branch of the submodule to point this PR to I am getting other non merged changes in the submodule ? There is another open PR to wremnants-data, so I wonder what would happen with them before they are merged

**Comment by cippy** [comment]
For independent reasons I have run the WLike from the same branch used to open this PR, where I moved the commit of the submodule, and I also got a change in the central values. This makes no sense to me, I really think that changing the submodule to a non merged commit was not a good idea, it is definitely doing strange things.

**Comment by bendavid** [comment]
No the commit for wremnants-data is correct in the sense that it has only your change on top of the current master branch as expected.

**Comment by cippy** [comment]
ok, I've just run the Wlike locally, because I wanted to check the prefit uncertainty band. I ran from the same branch as used for this PR, once with the new file and once overriding it to get the previous one again. I see no change in yields, while CI apparently sees small changes also for Wlike. Strange, is there any randomization that could change the used events at run time ? Or maybe a temporary glitch such that some events were lost in one case ?

**Comment by bendavid** [comment]
No the CI really should be reproducible (and it has been for other PR's recently)

**Comment by bendavid** [comment]
The issue is that this is inadvertently pulling in the problematic scetlib+dyturbo corrections from https://gitlab.cern.ch/cms-wmass/wremnants-data/-/merge_requests/66 and https://github.com/WMass/WRemnants/pull/491 which have (at least) a mismatch between the CS model parameters and the version of the scetlib code used.

**Comment by bendavid** [comment]
Yes @kdlong and I are discussing it

**Comment by cippy** [comment]
I updated both the submodule's commit and the code (merging the latest central changes), let's see if it works now. No change in central values should be seen.

**Comment by cippy** [comment]
So now the central values of histograms are equal to those of the reference run.

This PR (latest run): https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/PR497/2024_07_24/

Reference run: https://cmsmwbot.web.cern.ch/WMassAnalysis/PRValidation/ReferenceRuns/2024_07_24_c989d35/

The red line for the uncorrected MC is weird, but at least it's the same for both.

Uncertainty for eff_syst increases, which some interplay with other groups like PDFs which could arise from the low stat and the dependence on eta (from local tests with full stat the changes were small on other groups). All things considered it might be reasonable, though.

**Comment by bendavid** [comment]
Ok now the CI has no change in the central value and small changes in the impacts as expected.

**Pull request merged**
