### PR TITLE
Migrate data files to new wremnants-data submodule with lfs

### PR DESCRIPTION
**Pull request by bendavid**
Data files are migrated to a new wremnents-data submodule where they use git lfs for large files.  A submodule is needed because github has bandwidth limits for this feature, so we would otherwise need to move the main WRemnants repository to gitlab (and break the ci).

Users probably have to execute (once) "git lfs install" to work with the updated setup.

### CODE REVIEW

**Comment by bendavid** [comment]
This should be ok to merge now.

**Comment by kdlong** [comment]
Probably a good idea to add the needed setup command to the README. Or if there's a way to check if it's ever been run, it could go in setup.sh

**Comment by bendavid** [comment]
setup.sh is unfortunately "too late" to run the command, since the wremnants-data submodule has already been run by this point, but yes will add it the readme

**Comment by bendavid** [comment]
I'm closing this for now because I think there's a way to keep the data in the same repo but point the lfs storage to a separate place (on cern gitlab).

This would avoid the submodule and ease development.  I'll reopen this if the alternative ends up being problematic.

**Comment by bendavid** [comment]
Ok this can actually be merged now.

**Pull request merged**
