### PR TITLE
Overhaul of theory corrections (including by helicity) and plotting

### PR DESCRIPTION
**Pull request by kdlong**
* Addition of metadata dict to the analysis and correction outputs
* Implement reading of several generator outputs into boost hist
* Improved set of scripts to plot gen comparisons
* Improved implementation correction procedure that can take outputs from multiple generators
* implemented correction procedure by angular coefficient

### CODE REVIEW

**Comment by cippy** [comment]
In CardTool.py one has to replace the old OutputTools to the new output_tools (in the import and usage in the code).

Other than that, I could successfully run both scripts/histmakers/mw_with_mu_eta_pt.py and scripts/combine/setupCombineWMass.py (I am still checking if all outputs make sense, though), so I would say the PR can be merged

**Comment by kdlong** [comment]
> In CardTool.py one has to replace the old OutputTools to the new output_tools (in the import and usage in the code).
> 
> Other than that, I could successfully run both scripts/histmakers/mw_with_mu_eta_pt.py and scripts/combine/setupCombineWMass.py (I am still checking if all outputs make sense, though), so I would say the PR can be merged

Good point, done

**Review by cippy — COMMENTED** [review]
https://github.com/WMass/WRemnants/pull/69/files#diff-d4a110c5575451b61b90d23bb532ed889f3d41f6e1784d7a2bafe8c1f950d4e5R59

Does this snippet have to apply only to Z even in the W histogram maker?

**Comment by cippy** [comment]
When running the Wlike histogram maker, there seems to be an issue with the usage of the recoil corrections.  Based on the error messages a shared library might not have been loaded correctly, and then I get a ton of messages like

[nGaussian::findRoot]: initial interval does not bracket a root (fa=7.15803e-08, fb=1, pval=1.73638e-07, xMin=-500, xMax=500)

It works if using option --no_recoil for now

**Comment by kdlong** [comment]
> When running the Wlike histogram maker, there seems to be an issue with the usage of the recoil corrections. Based on the error messages a shared library might not have been loaded correctly, and then I get a ton of messages like
> 
> [nGaussian::findRoot]: initial interval does not bracket a root (fa=7.15803e-08, fb=1, pval=1.73638e-07, xMin=-500, xMax=500)
> 
> It works if using option --no_recoil for now

Right, but it's not actually an error, just a noisy warning. Could be turned off here: https://github.com/WMass/WRemnants/blob/main/wremnants/include/lowpu_recoil.h#L173

**Comment by kdlong** [comment]
> https://github.com/WMass/WRemnants/pull/69/files#diff-d4a110c5575451b61b90d23bb532ed889f3d41f6e1784d7a2bafe8c1f950d4e5R59
> 
> Does this snippet have to apply only to Z even in the W histogram maker?

Working on updating the corrections for W now

**Pull request merged**
