### PR TITLE
Add width uncertainty on W and Z

### PR DESCRIPTION
**Pull request by davidwalter2**
Weights for different W or Z boson widths are stored in the ntuples (branch "MEParamWeightAltSet1"). In this PR the weights are propagated in the histmaker and cardmaker to assess the corresponding uncertainty.

### CODE REVIEW

**Comment by davidwalter2** [comment]
I noticed the weight corresponding to the PDG width is in general not 1 ("MEParamWeightAltSet1[3]" in the root file), do we have to apply that weight to the nominal to reweight to the PDF width?

**Comment by kdlong** [comment]
@mseidel42 do you remember how we set this up? I think the widths are the PDG ones+running width correction, right? Is it expected for one of the width variations to match the nominal?

Width variations for reference: https://github.com/mseidel42/genproductions/blob/minnlo/bin/Powheg/runcmsgrid_powheg.sh#L204

And the values for the sample
Screenshot 2023-07-18 at 11 17 31

**Comment by davidwalter2** [comment]
To Josh, the width seems to mainly have a normalization effect and is completely negligible in the W fit, but it gets a sizable impact in the combined W + dilepton fit, I think because the width can change the normalization for only the W region. 

Thanks for the clarification Markus, in principle we would have two uncertainties for the width, right? For the uncertainty from the PDG combination we could either take this uncertainty on top of the current central value (by multiplying with the ratio 2.043/2.085 and 2.127/2.085) Or by reweighting our nominal value the the PDG combination and doing the ratio multiplication on the EW uncertaintes

**Comment by cippy** [comment]
Are these nuisance parameters supposed to be used when fitting stat only (with the mass nuisance of course) ? If not, I would move their definition in setupCombineWmass after the setting of the stat-only card, which only includes the actual mass variation.

**Comment by davidwalter2** [comment]
As discussed yesterday I think we concluded to not use them in our nominal fit but have them optional, I will make some updates for this, also moving them further down then.

**Comment by davidwalter2** [comment]
I think we could merge this now

**Pull request merged**
