### PR TITLE
Add powheg EW variations and other updates on EW uncertainties

### PR DESCRIPTION
**Pull request by davidwalter2**
Two variations from powheg NLO QCD + EW are added for the Z in wremnants-data [here](https://gitlab.cern.ch/cms-wmass/wremnants-data/-/merge_requests/36) 
Since studies have shown large impacts that are yet not understood, they are not added by default. 
- One variations aiming to cover the ISR+virtual EW uncertainty
- One variations aiming to cover the uncertainty from EW ISR effects

The ew theory corrections have been further updated in wremnants-data [here](https://gitlab.cern.ch/cms-wmass/wremnants-data/-/merge_requests/37)
- The horace and winhac corrections are updated by shifting the bin edges of the post fsr mW value by -30MeV according to wrong W mass values in those samples with versions < v5; The difference was checked and found to be negligible (third digit)
- The binning in mass for the corrections have been updated where each 4 bins are merged into 1 since to have less statistical fluctuations in the corrections, this slightly reduces the constraints in the fit and slightly increases the uncertainty, indicating that the binning was indeed too aggressive. 

For the fits, default EW uncertainties are adapted:
- The FSR uncertainty is estimated using two variations, consistently in the same way for the W and the Z: 1) horace vs photos and 2) photos ME corrections on/off
- The virtual EW uncertainties are estimated differently for W and Z: Winhac is used for the W while powheg fixed order is used for the Z
- No ISR uncertainty for now

The photon-induced background had previously no uncertainty assigned, a normalization uncertainty of 100% is added. The impact in a full stat fit is 0.11MeV (constraint to 0.88) for the Z dilepton mll fit and 0.09MeV (constraint to 0.88) for the mw fit,I didn't check the wlike fit. The impact is negligible but nevertheless, I think it should be added.

Small updates on scripts used to produce and verify these variations

### CODE REVIEW

**Comment by davidwalter2** [comment]
So the variations are just added to the list of possible theoryCorrections but they are not used in by default, so the PRValidation results are exactly the same. From my side it can be merged.

**Comment by bendavid** [comment]
As discussed I would prefer not to enable this ISR uncertainty by default.

**Comment by davidwalter2** [comment]
Okay, I have updated the PR and it's descriptions as discussed. For the W, the winhac uncertainty seems to be a bit larger than from previously horace but this might be an artefact due to the small number of files used in the CI.

**Comment by davidwalter2** [comment]
Hmm the impact on mW from winhac is 5.36MeV with full stat, I will do some further checks on this

**Comment by davidwalter2** [comment]
PR validation looks as expected, I think this is ready for review/merge

**Pull request merged**
